// <auto-generated />
namespace Project400_TransactEase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class VatAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VatAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202511180414575_VatAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
